# This is a basic workflow to help you get started with Actions

name: style_check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  style-check:
    - name: Checking style of the .py files
    - runs-on: ubuntu-latest

  steps:
      - name: download code from repo
        uses: actions/checkout@v4

      - name: python installing
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pycodestyle
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run pycodestyle
        run: |
            echo "start checking"
            pycodestyle --ignore=E501
